$terminal = foot
$fileManager = thunar
$displayManager = nwg-displays
$menu = wofi --show drun
$browser = firefox

# Monitors and workspaces are handled by nwg-displays
source = monitors.conf
source = workspaces.conf

source = hyprland/autostart.conf
source = hyprland/layout.conf
source = hyprland/decoration.conf
source = hyprland/animation.conf
source = hyprland/input.conf
source = hyprland/keybinding.conf
source = hyprland/misc.conf

env = HYPRSHOT_DIR,Images/screenshots

# Set dark theme for other applications
exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
